### ISSUE TITLE
String -> String Map

### ISSUE THREAD

**Issue by spar36** [az0977776/cs4500-a1p2-design#12]
Please implement a String -> String map spec, along side your Object -> Object map.

" Lastly, your Map should support mapping Strings to Strings and generally Object to Object." - A2

**Comment by az0977776** [comment]
Strings are a subclass of Objects

**Comment by spar36** [comment]
Piazza thread https://piazza.com/class/k51bluky59n2jr?cid=331 specifically cover this.

Having all types return a object would mean that they need to be cast whenever you do a get.

In the comments, Vitek specifically pushes that that is not an elegant design and that there should be different maps/arrays/queues based off of what it holds. 
 
The string -> string can inherit from Object -> object, but there needs to be the spec that has those types.


I know this is annoying and is solved with templates, but we aren't allowed to use them. -_-

**Comment by barthch** [comment]
Technically, the current specification does support String -> String. If the user of our Map wants to get a String out, it is part of the specs for them to have to cast it.

This is because we do not want to force you to also implement the String -> Object or Object -> String. For Example, we also run into issues when we try to extend Map to new objects like handling String -> Array (or whatever other future class we implement for map) and then need to permute all pairings of maps. 

This definition of map is able to handle any subclass of Object to and subclass of object and is much more flexible.
